# App config
app:
  name: kirin
  short:
    url:
      domain: 996.icu
  custom:
    url:
      max: 3

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: short_url_user
    password: welcome
    url: jdbc:mysql://127.0.0.1:3306/short_url_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 51MB
  session:
    timeout: 3d

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

server:
  servlet:
    context-path: /api
  port: 8080


logging:
  file: log4j2.yaml