package com.hisoka.mybatis.pojo;

import java.util.Date;

public class SShortUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.short_id
     *
     * @mbg.generated
     */
    private String shortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.source_url_hash
     *
     * @mbg.generated
     */
    private String sourceUrlHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_short_url.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.id
     *
     * @return the value of s_short_url.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.id
     *
     * @param id the value for s_short_url.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.short_id
     *
     * @return the value of s_short_url.short_id
     *
     * @mbg.generated
     */
    public String getShortId() {
        return shortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.short_id
     *
     * @param shortId the value for s_short_url.short_id
     *
     * @mbg.generated
     */
    public void setShortId(String shortId) {
        this.shortId = shortId == null ? null : shortId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.source_url_hash
     *
     * @return the value of s_short_url.source_url_hash
     *
     * @mbg.generated
     */
    public String getSourceUrlHash() {
        return sourceUrlHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.source_url_hash
     *
     * @param sourceUrlHash the value for s_short_url.source_url_hash
     *
     * @mbg.generated
     */
    public void setSourceUrlHash(String sourceUrlHash) {
        this.sourceUrlHash = sourceUrlHash == null ? null : sourceUrlHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.source_url
     *
     * @return the value of s_short_url.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.source_url
     *
     * @param sourceUrl the value for s_short_url.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.is_delete
     *
     * @return the value of s_short_url.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.is_delete
     *
     * @param isDelete the value for s_short_url.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.gmt_modify
     *
     * @return the value of s_short_url.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.gmt_modify
     *
     * @param gmtModify the value for s_short_url.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_short_url.gmt_create
     *
     * @return the value of s_short_url.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_short_url.gmt_create
     *
     * @param gmtCreate the value for s_short_url.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}