package com.hisoka.mybatis.mapper;

import com.hisoka.mybatis.pojo.SShortUrl;
import com.hisoka.mybatis.pojo.SShortUrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SShortUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    long countByExample(SShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int deleteByExample(SShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int insert(SShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int insertSelective(SShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    List<SShortUrl> selectByExample(SShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    SShortUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SShortUrl record, @Param("example") SShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SShortUrl record, @Param("example") SShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_short_url
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SShortUrl record);
}